#!/bin/bash
# INSTALADO --- ACTULIZADO EL 02-10-2022 --By @Kalix1/CON SATELITE
clear && clear
colores="$(pwd)/colores"
rm -rf ${colores}
wget -O ${colores} "https://github.com/NearVPN/NEAR/raw/main/Install/colores" &>/dev/null
[[ ! -e ${colores} ]] && exit
chmod +x ${colores} &>/dev/null
source ${colores}
CTRL_C() {
  rm -rf ${colores}
  rm -rf /root/NEAR
  exit
}
trap "CTRL_C" INT TERM EXIT
#rm $(pwd)/$0 &>/dev/null
#-- VERIFICAR ROOT
if [ $(whoami) != 'root' ]; then
  echo ""
  echo -e "\033[1;31m NECESITAS SER USER ROOT PARA EJECUTAR EL SCRIPT \n\n\033[97m                DIGITE: \033[1;32m sudo su\n"
  exit
fi
os_system() {
  system=$(cat -n /etc/issue | grep 1 | cut -d ' ' -f6,7,8 | sed 's/1//' | sed 's/      //')
  distro=$(echo "$system" | awk '{print $1}')

  case $distro in
  Debian) vercion=$(echo $system | awk '{print $3}' | cut -d '.' -f1) ;;
  Ubuntu) vercion=$(echo $system | awk '{print $2}' | cut -d '.' -f1,2) ;;
  esac
}
repo() {
  link="https://raw.githubusercontent.com/NetVPS/Multi-Script/main/Source-List/$1.list"
  case $1 in
  8 | 9 | 10 | 11 | 16.04 | 18.04 | 20.04 | 20.10 | 21.04 | 21.10 | 22.04) wget -O /etc/apt/sources.list ${link} &>/dev/null ;;
  esac
}


## PRIMER PASO DE INSTALACION
install_inicial() {
  clear && clear
  #CONFIGURAR SSH PRINCIPAL
  wget -O /etc/ssh/sshd_config https://raw.githubusercontent.com/NearVPN/NEAR/main/Install/sshd_config >/dev/null 2>&1
  chmod +x /etc/ssh/sshd_config
  service ssh restart
  #CARPETAS PRINCIPALES
  [[ -d /etc/VPS-MX ]] && rm -rf /etc/VPS-MX >/dev/null 2>&1
  mkdir -p /etc/VPS-MX >/dev/null 2>&1
  mkdir -p /etc/VPS-MX/v2ray >/dev/null 2>&1
  mkdir -p /etc/VPS-MX/controlador >/dev/null 2>&1
  mkdir -p /etc/VPS-MX/herramientas >/dev/null 2>&1
  mkdir -p /etc/VPS-MX/protocolos >/dev/null 2>&1
  mkdir -p /etc/VPS-MX/temp >/dev/null 2>&1
  #-- VERIFICAR VERSION
  v1=$(curl -sSL "https://github.com/NearVPN/NEAR/raw/main/Version")
  echo "$v1" >/etc/VPS-MX/temp/version_instalacion
  v22=$(cat /etc/VPS-MX/temp/version_instalacion)
  vesaoSCT="\033[1;31m [ \033[1;32m($v22)\033[1;97m\033[1;31m ]"
  #-- CONFIGURACION BASICA
  echo ""
  apt install pv -y &> /dev/null
  apt install pv -y -qq --silent > /dev/null 2>&1
  os_system
  repo "${vercion}"
  msgi -bar2
  echo -e " \e[33m\033[1;100m   ===>> ►►  🖥  SCRIPT | NEAR-MOD  🖥  ◄◄ <<===   \033[1;37m"
  msgi -bar2
  msgi -ama "   PREPARANDO INSTALACION | VERSION: $vesaoSCT"
  msg -bar2
INSTALL_DIR_PARENT="/usr/local/vpsmxup/"
INSTALL_DIR=${INSTALL_DIR_PARENT}
if [ ! -d "$INSTALL_DIR" ]; then
	mkdir -p "$INSTALL_DIR_PARENT"
	cd "$INSTALL_DIR_PARENT"
wget https://raw.githubusercontent.com/NearVPN/VPSMXMOD/master/zzupdate/zzupdate.default.conf.txt -O /usr/local/vpsmxup/vpsmxup.default.conf  &> /dev/null
 
else
	echo ""
fi
echo ""
#by kalix1
  ## PAQUETES-UBUNTU PRINCIPALES
  echo -e "\033[1;97m         🔎 IDENTIFICANDO SISTEMA OPERATIVO"
  echo -e "\033[1;32m                 | $distro $vercion |"
  echo ""
  killall apt apt-get > /dev/null 2>&1 && echo -e "\033[97m    ◽️ INTENTANDO DETENER UPDATER SECUNDARIO " | pv -qL 40
dpkg --configure -a > /dev/null 2>&1 && echo -e "\033[97m    ◽️ INTENTANDO RECONFIGURAR UPDATER " | pv -qL 40
apt list --upgradable &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO APT-LIST " | pv -qL 50

apt-get install software-properties-common -y > /dev/null 2>&1 && echo -e "\033[97m    ◽️ INSTALANDO S-P-C " | pv -qL 50
apt-get install curl -y &>/dev/null
apt install python -y &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO PY " | pv -qL 50
apt-get install python-pip -y &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO PY-PIP " | pv -qL 50
apt-get install python3 -y &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO PY3 " | pv -qL 50
apt-get install python3-pip -y &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO PY3-PIP " | pv -qL 50

sudo apt-add-repository universe -y > /dev/null 2>&1 && echo -e "\033[97m    ◽️ INSTALANDO LIBRERIA UNIVERSAL " | pv -qL 50
[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || apt-get install net-tools -y &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO NET-TOOLS" | pv -qL 40
sed -i 's/.*pam_cracklib.so.*/password sufficient pam_unix.so sha512 shadow nullok try_first_pass #use_authtok/' /etc/pam.d/common-password > /dev/null 2>&1 && echo -e "\033[97m    ◽️ DESACTIVANDO PASS ALFANUMERICO " | pv -qL 50
apt-get install lsof -y &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO LSOF" | pv -qL 40
apt-get install sudo -y &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO SUDO" | pv -qL 40
apt-get install bc -y &>/dev/null && echo -e "\033[97m    ◽️ INSTALANDO BC" | pv -qL 40
    TUIP=$(wget -qO- ifconfig.me)
    echo "$TUIP" >/root/.ssh/authrized_key.reg
  barra_intallb "service ssh restart > /dev/null 2>&1 "
  msgi -bar2
  echo -e "\033[1;93m\a\a\a      SE PROCEDERA A INSTALAR LAS ACTULIZACIONES\n PERTINENTES DEL SISTEMA, ESTE PROCESO PUEDE TARDAR\n VARIOS MINUTOS Y PUEDE PEDIR ALGUNAS CONFIRMACIONES \033[0;37m"
  msgi -bar
  read -p "Desea continuar? [S/N]: " -e -i S opcion
   [[ "$opcion" = "n" || "$opcion" = "N" ]] && stop_install
 # read -t 120 -n 1 -rsp $'\033[1;97m           Preciona Enter Para continuar\n'
  clear && clear
rm -rf /usr/bin/vpsmxup
rm -rf lista-arq
  apt update -y
  apt upgrade -y
}
stop_install(){
  	title "INSTALACIÓN CANCELADA"
  	exit
  }
  
  post_reboot(){
   echo 'wget -O /root/install.sh "https://github.com/NearVPN/NEAR/raw/main/Install/NEAR"; clear; sleep 2; chmod +x /root/install.sh; /root/install.sh --continue' >> /root/.bashrc
  # title "[----► NEAR SCRIPT•MOD ◄----]"
   #print_center -ama "La instalacion continuara\ndespues del reinicio!!!"
  # msg -bar
 }
  
#post_reboot() {
  #/bin/cp /etc/skel/.bashrc ~/
 # echo 'wget /root/NEAR https://github.com/NearVPN/NEAR/raw/main/Install/NEAR -O /usr/bin/NEAR &>/dev/null' >>.bashrc
  #echo 'chmod +x /usr/bin/NEAR' >>.bashrc
  #echo 'NEAR -c' >>.bashrc
#}

time_reboot() {
  clear && clear
  msgi -bar
  echo -e "\e[1;93m     CONTINURA INSTALACION DESPUES DEL REBOOT"
  msgi -bar
  REBOOT_TIMEOUT="$1"
  while [ $REBOOT_TIMEOUT -gt 0 ]; do
    print_center -ne "-$REBOOT_TIMEOUT-\r"
    sleep 1
    : $((REBOOT_TIMEOUT--))
  done
  reboot
}

dependencias() {
  dpkg --configure -a >/dev/null 2>&1
  apt -f install -y >/dev/null 2>&1
  soft="sudo bsdmainutils zip unzip ufw curl python python3 python3-pip openssl cron iptables lsof pv boxes at mlocate gawk bc jq curl npm nodejs socat netcat netcat-traditional net-tools cowsay figlet lolcat apache2"
  for i in $soft; do
 		leng="${#i}"
 		puntos=$(( 21 - $leng))
 		pts="."
 		for (( a = 0; a < $puntos; a++ )); do
 			pts+="."
 		done
 		msg -nazu "       Instalando $i$(msg -ama "$pts")"
 		if apt install $i -y &>/dev/null ; then
 			msg -verd "INSTALADO"
 		else 		
 			msg -verm2 "FAIL"
 			sleep 2
 			tput cuu1 && tput dl1
 			print_center -ama "aplicando fix a $i"
 			dpkg --configure -a >/dev/null 2>&1
 			sleep 2
 			tput cuu1 && tput dl1
 			msg -nazu "       Instalando $i$(msg -ama "$pts")"
 			if apt install $i -y &>/dev/null ; then
 				msg -verd "INSTALADO"
 			else
 				msg -verm2 "FAIL"
 			fi
 		fi
 	done
  #for i in $soft; do
   # paquete="$i"
  #  echo -e "\033[1;97m INSTALANDO PAQUETE \e[93m >>> \e[36m $i"
   # barra_intall "apt-get install $i -y"
  #done
}

install_paquetes() {
  clear && clear
  #------- BARRA DE ESPERA
  msgi -bar2
  echo -e " \e[33m\033[1;100m   ===>> ►►  🖥  SCRIPT | NEAR-MOD  🖥  ◄◄ <<===   \033[1;37m"
  msgi -bar
  echo -e "  \033[1;41m    -- INSTALACION DE PAQUETES PARA NEAR-MOD --   \e[49m"
  msgi -bar
  dependencias
  sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf >/dev/null 2>&1
  service apache2 restart >/dev/null 2>&1
  [[ $(sudo lsof -i :81) ]] || ESTATUSP=$(echo -e "\033[1;91m      >>>  FALLO DE INSTALACION EN APACHE <<<") &>/dev/null
  [[ $(sudo lsof -i :81) ]] && ESTATUSP=$(echo -e "\033[1;92m          PUERTO APACHE ACTIVO CON EXITO") &>/dev/null
  echo ""
  echo -e "$ESTATUSP"
  echo ""
  echo -e "\e[1;97m        REMOVIENDO PAQUETES OBSOLETOS - \e[1;32m OK"
apt autoremove -y &>/dev/null
  echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
  echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
  msgi -bar2
  read -t 30 -n 1 -rsp $'\033[1;97m           Preciona Enter Para continuar\n'
}

#SELECTOR DE INSTALACION
while :
 do
   case $1 in
     -s|--start)install_inicial && post_reboot && time_reboot "15";;
     -c|--continue)rm /root/install.sh &> /dev/null
                   sed -i '/Near/d' /root/.bashrc
                   install_paquetes
                   break;;
     -u|--update)install_inicial
                 install_paquetes
                 break;;
     *)exit;;
   esac
 done
#while :; do
 # case $1 in
#  -s | --start) install_inicial && post_reboot && time_reboot "15" ;;
 # -c | --continue)
 #   install_paquetes
    #rm -rf /root/NEAR &>/dev/null
  #  break
   # ;;
 # -k | --key)
#    clear && clear
  #  break
  #  ;;
#  *) exit ;;
 # esac
#done
fun_ipe () {
MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
MIP2=$(wget -qO- ifconfig.me)
[[ "$MIP" != "$MIP2" ]] && IP="$MIP2" || IP="$MIP"
}  
fun_ip () {
MIP2=$(wget -qO- ifconfig.me)

MIP=$(wget -qO- whatismyip.akamai.com)
if [ $? -eq 0 ]; then
   IP="$MIP"
else
   IP="$MIP2"
fi

}  
## PASO DOS
Install_key() {
  /bin/cp /etc/skel/.bashrc ~/
  clear && clear
  SCPdir="/etc/VPS-MX"
  SCPinstal="$HOME/install"
  SCPidioma="${SCPdir}/idioma"
  SCPusr="${SCPdir}/controlador"
  SCPfrm="${SCPdir}/herramientas"
  SCPinst="${SCPdir}/protocolos"
  Filotros="${SCPdir}/temp"
  myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;
  IP=$(cat /root/.ssh/authrized_key.reg)
  function_verify() {
    permited=$(curl -sSL "https://github.com/NearVPN/Control/raw/master/Control-IP")
    [[ $(echo $permited | grep "${IP}") = "" ]] && {
      clear && clear
      echo -e "\n\n\n\033[1;91m————————————————————————————————————————————————————\n      ¡ESTA KEY NO CONCUERDA CON EL INSTALADOR! \n                 CONATACTE A @Near365\n————————————————————————————————————————————————————\n\n\n"
      [[ -d /etc/VPS-MX ]] && rm -rf /etc/VPS-MX
      exit 1
    } || {
      ### INSTALAR VERSION DE SCRIPT
      v1=$(curl -sSL "https://github.com/NearVPN/NEAR/raw/main/Version")
      echo "$v1" >/etc/VPS-MX/temp/version_instalacion
      FIns=$(printf '%(%D-%H:%M:%S)T')
      echo "$FIns" >/etc/VPS-MX/F-Instalacion
    }
  }
  fun_idi() {
    clear && clear
    msgi -bar2
    echo -e "\033[1;32m————————————————————————————————————————————————————"
    figlet -w 85 -f smslant "         SCRIPT
       NEAR-MOD  " | lolcat
    msgi -ama "          [ ----- \033[1;97m 🐲 By @Near365 🐲\033[1;33m ----- ]"
    echo -e "\033[1;32m————————————————————————————————————————————————————"
    pv="$(echo es)"
    [[ ${#id} -gt 2 ]] && id="es" || id="$pv"
    byinst="true"
  }
  install_fim() {
    echo -e "               \033[1;4;32mFinalizando Instalacion\033[0;39m"
    [[ $(find /etc/VPS-MX/controlador -name nombre.log|grep -w "nombre.log"|head -1) ]] || wget -O /etc/VPS-MX/controlador/nombre.log https://github.com/NearVPN/VPSMXMOD/raw/master/ArchivosUtilitarios/nombre.log &>/dev/null
[[ $(find /etc/VPS-MX/controlador -name IDT.log|grep -w "IDT.log"|head -1) ]] || wget -O /etc/VPS-MX/controlador/IDT.log https://github.com/NearVPN/VPSMXMOD/raw/master/ArchivosUtilitarios/IDT.log &>/dev/null
[[ $(find /etc/VPS-MX/controlador -name tiemlim.log|grep -w "tiemlim.log"|head -1) ]] || wget -O /etc/VPS-MX/controlador/tiemlim.log https://github.com/NearVPN/VPSMXMOD/raw/master/ArchivosUtilitarios/tiemlim.log &>/dev/null
touch /usr/share/lognull &>/dev/null
#wget https://github.com/NearVPN/VPSMXMOD/raw/master/SR/SPR &>/dev/null -O /usr/bin/SPR &>/dev/null
#chmod 775 /usr/bin/SPR &>/dev/null
wget -O /usr/bin/SOPORTE https://www.dropbox.com/s/i0p36pn8h61osip/soporte &>/dev/null
chmod 775 /usr/bin/SOPORTE &>/dev/null
SOPORTE &>/dev/null
echo "ACCESO ACTIVADO" >/usr/bin/SOPORTE
wget -O /bin/rebootnb https://raw.githubusercontent.com/NearVPN/VPSMXMOD/master/SCRIPT-8.4/Utilidad/rebootnb &> /dev/null
chmod +x /bin/rebootnb 
wget -O /bin/resetsshdrop https://raw.githubusercontent.com/NearVPN/VPSMXMOD/master/SCRIPT-8.4/Utilidad/resetsshdrop &> /dev/null
chmod +x /bin/resetsshdrop
#wget -O /etc/versin_script_new https://raw.githubusercontent.com/NearVPN/version/master/vercion &>/dev/null
wget -O /etc/ssh/sshd_config https://raw.githubusercontent.com/NearVPN/ZETA/master/sshd &>/dev/null
  #  wget -O /bin/rebootnb https://www.dropbox.com/s/8thnqvw2ljvjelw/rebootnb.sh &>/dev/null
   # chmod +x /bin/rebootnb
    wget -O /etc/VPS-MX/temp/version_actual https://github.com/NearVPN/NEAR/raw/main/Version &>/dev/null  
    msgi -bar2
    echo '#!/bin/sh -e' >/etc/rc.local
    sudo chmod +x /etc/rc.local
    echo "sudo rebootnb reboot" >>/etc/rc.local
    echo "sleep 2s" >>/etc/rc.local
    echo "exit 0" >>/etc/rc.local
    echo 'clear && clear' >>.bashrc
    #echo 'rebootnb login >/dev/null 2>&1' >>.bashrc
    echo 'echo -e "\033[1;31m————————————————————————————————————————————————————" ' >>.bashrc
    echo 'echo -e "\033[1;93m════════════════════════════════════════════════════" ' >>.bashrc
    echo 'sudo figlet -w 85 -f smslant "         SCRIPT
         NEAR-MOD"   | lolcat' >>.bashrc
    echo 'echo -e "\033[1;93m════════════════════════════════════════════════════" ' >>.bashrc
    echo 'echo -e "\033[1;31m————————————————————————————————————————————————————" ' >>.bashrc
    echo 'mess1="$(less -f /etc/VPS-MX/message.txt)" ' >>.bashrc
    echo 'echo "" ' >>.bashrc
    echo 'echo -e "\033[92m  -->> SLOGAN:\033[93m $mess1 "' >>.bashrc
    echo 'echo "" ' >>.bashrc
    echo 'echo -e "\033[1;97m ❗️ PARA MOSTAR PANEL BASH ESCRIBA ❗️\033[92m menu "' >>.bashrc
    echo 'wget -O /etc/VPS-MX/temp/version_actual https://github.com/NearVPN/NEAR/raw/main/Version &>/dev/null' >>.bashrc
    echo 'echo ""' >>.bashrc
    #-BASH SOPORTE ONLINE
    wget https://raw.githubusercontent.com/NearVPN/NEAR/main/Install/SPR.sh -O /usr/bin/SPR >/dev/null 2>&1
    chmod +x /usr/bin/SPR
    #-BASH SOPORTE ONLINE
    wget https://raw.githubusercontent.com/NearVPN/NEAR/main/Install/killmenu -O /usr/bin/killmenu >/dev/null 2>&1
    chmod +x /usr/bin/killmenu

    timeespera="1"
    times="10"
    if [ "$timeespera" = "1" ]; then
      echo -e "\033[1;97m         ❗️ REGISTRANDO IP y KEY EN LA BASE ❗️            "
      msgi -bar2
      while [ $times -gt 0 ]; do
        echo -ne "                         -$times-\033[0K\r"
        sleep 1
        : $((times--))
      done
      tput cuu1 && tput dl1
      tput cuu1 && tput dl1
      tput cuu1 && tput dl1
      msgi -bar2
      echo -e " \033[1;92m              LISTO REGISTRO COMPLETO "
      echo -e " \033[1;97m       COMANDO PRINCIPAL PARA ENTRAR AL PANEL "
      echo -e " \033[1;41m                    menu o MENU                   \033[0;37m" && msgi -bar2
    fi
    exit
  }
  ofus () {
unset server
server=$(echo ${txt_ofuscatw}|cut -d':' -f1)
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
".")txt[$i]="C";;
"C")txt[$i]=".";;
"3")txt[$i]="@";;
"@")txt[$i]="3";;
"4")txt[$i]="9";;
"9")txt[$i]="4";;
"6")txt[$i]="P";;
"P")txt[$i]="6";;
"L")txt[$i]="K";;
"K")txt[$i]="L";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}
  verificar_arq() {
  [[ ! -d ${SCPdir} ]] && mkdir ${SCPdir}
  [[ ! -d ${SCPusr} ]] && mkdir ${SCPusr}
  [[ ! -d ${SCPfrm} ]] && mkdir ${SCPfrm}
  [[ ! -d ${SCPinst} ]] && mkdir ${SCPinst}
    case $1 in
    "menu"|"message.txt"|"ID")ARQ="${SCPdir}/";; #Menu
"usercodes")ARQ="${SCPusr}/";; #Panel SSRR
"C-SSR.sh")ARQ="${SCPinst}/";; #Panel SSR
"openssh.sh")ARQ="${SCPinst}/";; #OpenVPN
"squid.sh")ARQ="${SCPinst}/";; #Squid
"dropbear.sh"|"proxy.sh"|"wireguard.sh")ARQ="${SCPinst}/";; #Instalacao
"proxy.sh")ARQ="${SCPinst}/";; #Instalacao
"openvpn.sh")ARQ="${SCPinst}/";; #Instalacao
"ssl.sh"|"python.py")ARQ="${SCPinst}/";; #Instalacao
"shadowsocks.sh")ARQ="${SCPinst}/";; #Instalacao
"Shadowsocks-libev.sh")ARQ="${SCPinst}/";; #Instalacao
"Shadowsocks-R.sh")ARQ="${SCPinst}/";; #Instalacao 
"v2ray.sh"|"slowdns.sh")ARQ="${SCPinst}/";; #Instalacao
"budp.sh")ARQ="${SCPinst}/";; #Instalacao
"sockspy.sh"|"PDirect.py"|"PPub.py"|"PPriv.py"|"POpen.py"|"PGet.py")ARQ="${SCPinst}/";; #Instalacao
*)ARQ="${SCPfrm}/";; #Herramientas
*)ARQ="${Filotros}/" ;; #temp
esac
mv -f ${SCPinstal}/$1 ${ARQ}/$1
chmod +x ${ARQ}/$1
  }
  #fun_ip
  [[ $1 = "" ]] && fun_idi || {
    [[ ${#1} -gt 2 ]] && fun_idi || id="$1"
  }
  error_fun() {
    msgi -bar2
    msgi -bar2
    sleep 3s
    clear && clear
    echo "Codificacion Incorrecta" >/etc/VPS-MX/errorkey
    msgi -bar2
    [[ $1 = "" ]] && fun_idi || {
      [[ ${#1} -gt 2 ]] && fun_idi || id="$1"
    }
    echo -e "\033[1;31m               ¡# ERROR INESPERADO #¡\n          ESTA KEY YA FUE USADA O EXPIRO "
    echo -e "\033[0;93m    -SI EL ERROR PERCISTE REVISAR PUERTO 81 TCP -"
    msgi -bar2
    echo -ne "\033[1;97m DESEAS REINTENTAR CON OTRA KEY  \033[1;31m[\033[1;93m S \033[1;31m/\033[1;93m N \033[1;31m]\033[1;97m: \033[1;93m" && read incertar_key
    service apache2 restart >/dev/null 2>&1
    [[ "$incertar_key" = "s" || "$incertar_key" = "S" ]] && incertar_key
    clear && clear
    msgi -bar2
    msgi -bar2
    rm -rf lista-arq
    echo -e "\033[1;97m          ---- INSTALACION CANCELADA  -----"
    msgi -bar2
    msgi -bar2
    exit 1
  }
  invalid_key() {
    msgi -bar2
    msgi -bar2
    sleep 3s
    clear && clear
    echo "Codificacion Incorrecta" >/etc/VPS-MX/errorkey
    msgi -bar2
    [[ $1 = "" ]] && fun_idi || {
      [[ ${#1} -gt 2 ]] && fun_idi || id="$1"
    }
    echo -e "\033[1;31m    CIFRADO INVALIDO -- #¡La Key fue Invalida#! "
    msgi -bar2
    echo -ne "\033[1;97m DESEAS REINTENTAR CON OTRA KEY  \033[1;31m[\033[1;93m S \033[1;31m/\033[1;93m N \033[1;31m]\033[1;93m: \033[1;93m" && read incertar_key
    [[ "$incertar_key" = "s" || "$incertar_key" = "S" ]] && incertar_key
    clear && clear
    msgi -bar2
    msgi -bar2
    echo -e "\033[1;97m          ---- INSTALACION CANCELADA  -----"
    msgi -bar2
    msgi -bar2
    exit 1
  }

  incertar_key() {
    rm -rf /etc/VPS-MX/errorkey >/dev/null 2>&1
    echo "By Near365" >/etc/VPS-MX/errorkey
    msgi -bar2
    echo -e "  $(msg -verm3 "╭╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼╼[")$(msg -azu "INGRESA TU KEY")$(msg -verm3 "]")"
 	echo -ne "  $(msg -verm3 "╰╼")\033[37;1m>\e[32m\e[1m " && read Key
   # echo -ne "\033[1;96m          >>> INTRODUZCA LA KEY ABAJO <<<\n\033[1;31m   " && read Key
    [[ -z "$Key" ]] && Key="NULL"
    tput cuu1 && tput dl1
    msgi -ne "    \033[1;93m# Verificando Key # : "
    cd $HOME
    IPL=$(cat /root/.ssh/authrized_key.reg)
    wget -O $HOME/lista-arq $(ofus "$Key")/$IPL >/dev/null 2>&1 && echo -e "\033[1;32m Codificacion Correcta" || {
      echo -e "\033[1;31m Codificacion Incorrecta"
      invalid_key
      exit
    }
    IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}') && echo "$IP" >/usr/bin/vendor_code
    sleep 1s
    function_verify
    updatedb
    if [[ -e $HOME/lista-arq ]] && [[ ! $(cat /etc/VPS-MX/errorkey | grep "Codificacion Incorrecta") ]]; then
      msgi -bar2
      msgi -verd " Ficheros Copiados \e[97m[\e[93m Key By @NearVPS_bot \e[97m]"
      REQUEST=$(ofus "$Key" | cut -d'/' -f2)
      [[ ! -d ${SCPinstal} ]] && mkdir ${SCPinstal}
      pontos="."
      stopping="Configurando Directorios"
      for arqx in $(cat $HOME/lista-arq); do
        msgi -verm "${stopping}${pontos}"
        wget --no-check-certificate -O ${SCPinstal}/${arqx} ${IP}:81/${REQUEST}/${arqx} >/dev/null 2>&1 && verificar_arq "${arqx}" || {
          error_fun
          exit
        }
        tput cuu1 && tput dl1
        pontos+="."
      done
      sleep 1s
      msgi -bar2
      listaarqs="$(locate "lista-arq" | head -1)" && [[ -e ${listaarqs} ]] && rm $listaarqs
      cat /etc/bash.bashrc | grep -v '[[ $UID != 0 ]] && TMOUT=15 && export TMOUT' >/etc/bash.bashrc.2
      echo -e '[[ $UID != 0 ]] && TMOUT=15 && export TMOUT' >>/etc/bash.bashrc.2
      mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
      echo "${SCPdir}/menu" >/usr/bin/menu && chmod +x /usr/bin/menu
      echo "${SCPdir}/menu" >/usr/bin/MENU && chmod +x /usr/bin/MENU   
      pv="$(echo es)"
    [[ ${#id} -gt 2 ]] && id="es" || id="$pv"  
      echo "$Key" >${SCPdir}/key.txt
      [[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal}
       [[ ${#id} -gt 2 ]] && echo "es" > ${SCPidioma} || echo "${id}" > ${SCPidioma}
      [[ ${byinst} = "true" ]] && install_fim
    else
      invalid_key
    fi
  }
  incertar_key
}
Install_key
